# Generated by Django 3.1.3 on 2021-02-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
    ]
